/*
 * Copyright 2000-2012 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;
import consulo.ui.migration.SwingImageRef;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class XpathIcons
{
	private static SwingImageRef load(String path)
	{
		return IconLoader.getIcon(path, XpathIcons.class);
	}

	public static final Icon Namespace = load("/icons/namespace.png"); // 21x21
	public static final Icon Tag = load("/icons/tag.png"); // 16x16
	public static final Image Xpath = load("/icons/xpath.png"); // 12x16
}
